baseURL = 'https://jainiea.github.com/'
title = 'Jainie A.'
author = "Val Manchinski"
copyright = "© 2025, Jainie A."
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true

# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]
[pagination]
  pagerSize = 3

[params]
  color = 'linen'
  twitter = 'JainieAI'
  instagram = 'jainie_ai'
  threads = 'jainie_ai' 
  youtube = 'EnglishWatchLearn'

avatar = 'moreimpress102@gmail.com'
  name = 'Jainie A.'
  bio = 'Discover fresh context'
# ------------------------------

# needed to  render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
#  [markup.highlight]
#    lineNos = true

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"   

[module]
  [[module.imports]]
    path = "github.com/nanxiaobei/hugo-paper"